name: Deploy to Firebase on merge
on:
    push:
        branches:
            - production
jobs:
    build_and_deploy:
        if: github.event.repository.full_name == 'thehereward/snapcup'
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: build react app
              run: cd app && npm ci && NODE_ENV=production npm run build
            - name: build functions
              run: cd functions && npm ci && npm run build
            - name: deploy firestore and functions
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only firestore,functions,hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PRODUCTION }}
            - name: Discord notification
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              uses: Ilshidur/action-discord@master
